import react from 'react';

// function Greet () {
//     return(
//         <h1>Hello Prince!</h1>
//     )
// }
// This is arror function.
export const Greet = () => <h1>This is generated by arrow function.</h1>

// export default Greet